module.exports = function resolveAbsoluteImport(importName) {
    const values = {
        initChaynsHelper: 'config/chaynsHelperConfig.js',
        DateTimeChooseButton: 'components/buttons/DateTimeChooseButton',
        UACGroupChooseButton: 'components/buttons/UACGroupChooseButton',
        ChaynsEditor: 'components/chayns-editor/ChaynsEditor',
        CenteredButtonContainer: 'components/containers/CenteredButtonContainer',
        CenteredContainer: 'components/containers/CenteredContainer',
        CenteredWaitCursor: 'components/containers/CenteredWaitCursor',
        DataRow: 'components/containers/DataRow',
        ErrorBoundary: 'components/error-boundary/ErrorBoundary',
        refresh: 'components/other/Refresh',
        RefreshComponent: 'components/other/RefreshComponent',
        ResizableWaitCursor: 'components/other/ResizableWaitCursor',
        SuspenseWaitCursor: 'components/other/SuspenseWaitCursor',
        RestrictedAccordion: 'components/restricted-accordion/RestrictedAccordion',
        hideCwFooter: 'functions/chaynsCalls/hideCwFooter',
        setViewMode: 'functions/chaynsCalls/setViewMode',
        chaynsCall: 'functions/chaynsCalls/chaynsCalls',
        // backgroundColorClass: '',
        // borderColorClass,
        // colorClass,
        // getChaynsColor,
        // getChaynsColorRgb,
        // hexToRgb,
        // mixChaynsColorRgb,
        chaynsDialog: 'functions/chaynsDialogs',
        copyOnClick: 'functions/copy',
        defaultErrorHandler: 'config/default-error-handler',
        generateUUID: 'functions/generateUid',
        // httpRequest,
        // HttpMethod,
        // handleRequest,
        // ResponseType,
        // RequestError,
        // LogLevel,
        showFailureAnimation: 'functions/statusAnimations/showSuccessAnimation',
        showSuccessAnimation: 'functions/statusAnimations/showFailureAnimation',
        // fnsFormat,
        // formatDate,
        // formatDateText,
        // removeTimeZoneOffset,
        // time,
        types: 'functions/types',
        // extend,
        showWaitCursor: 'functions/waitCursor',
        useTimeoutState: 'hooks/uniques/useTimeoutState',
        useUniqueEventListener: 'hooks/uniques/useUniqueEventListener',
        useUniqueInterval: 'hooks/uniques/useUniqueInterval',
        useUniqueTimeout: 'hooks/uniques/useUniqueTimeout',
        useElementProps: 'hooks/useElementProps',
        // removeCustomProps,
        useFullscreenTapp: 'hooks/useFullscreenTapp',
        useFunctionState: 'hooks/useFunctionState',
        useRefresh: 'hooks/useRefresh',
        userUser: 'hooks/useUser',
        useWebsocketService: 'hooks/useWebsocketService',
        localStorage: 'other/localStorageHelper',
        WebsocketClient: 'other/WsClient',
        TextStringMemo: 'textstring/TextStringMemo',
        // getAllTextStrings,
        // getTextStrings,
        // TextStringComplex,
        // useTextStrings,
        AsyncPromise: 'functions/AsyncPromise',
        createEnum: 'functions/createEnum',
        getHookState: 'functions/getHookState',
        shallowEqual: 'functions/shallowEqual'
    };

    if (!values[importName]) {
        throw new Error(`Unable to resolve ${importName} from chayns-helper. Please check the spelling. If it's not wrong please create an issue (https://github.com/chincoe/chayns-helper/issues).`);
    }

    return `chayns-helper/lib/${values[importName]}`;
};
